---
- name: Install Windows Updates
  hosts: all
  gather_facts: false
  become: true
  
  tasks:
  - name: Install all security updates with automatic reboots
    win_updates:
      category_names:
      - SecurityUpdates
    #  - CriticalUpdates
    #  - UpdateRollups
    #  - DefinitionUpdates
      reboot: yes
